### PR TITLE
20 import into separate account

### PR DESCRIPTION
**Pull request by 0marSalah**

### CODE REVIEW

**Comment by 0marSalah** [comment]
the first time users hit import, it will work fine without any errors

but the second time will cause duplicates and the importing will fail

waiting for @gobengo cuuid npm package to avoid duplicates

**Comment by gobengo** [comment]
> waiting for @gobengo cuuid npm package to avoid duplicates

@0marSalah I published it just now:
https://github.com/gobengo/cuuid-sha-256
https://www.npmjs.com/package/cuuid-sha-256

Look good?

**Comment by 0marSalah** [comment]
got an error when 
`import CUUIDSHA256 from 'cuuid-sha-256';
import { canonicalize } from 'json-canonicalize';`

`Error [ERR_MODULE_NOT_FOUND]: Cannot find module **'/Users/omar/Desktop/projects/activity-pub/hollo/node_modules/cuuid-sha-256/lib/index.js'** imported from /Users/omar/Desktop/projects/activity-pub/hollo/src/entities/importAccount.ts`

**Comment by gobengo** [comment]
@0marSalah Thanks for testing. Sorry it doesn't work. I believe it's because of this setting https://github.com/gobengo/cuuid-sha-256/blob/main/tsconfig.json#L15

Can't fix right now but will ASAP.

Basically that repo needs a PR that removes that setting so lib/index.js is emitted. But that will probably also require adjusting all the `import` statements to import `.js` suffix instead of `.ts`. And then maybe adjusting how some scripts are called to not rely on the experimental node.js ts type stripping.
(If that makes any sense to you, feel free to try the PR. Otherwise I will when I can)

**Comment by 0marSalah** [comment]
ok i will try, thanks

**Comment by 0marSalah** [comment]
@gobengo 

could you gimme the write permission to create the PR?

**Comment by gobengo** [comment]
@0marSalah I just published 1.1.3 with a fix.
image

patch: https://github.com/gobengo/cuuid-sha-256/commit/c62031eda28e01635977cab79fd2a736ce2a1774

**Pull request merged**
